sync-to-github:
  image: ubuntu:20.04
  script:
    - apt-get update -y
    - apt-get install git -y
    - git clone -b master --single-branch https://gitlab.com/kishore1307/blog.git
    - cd blog
    - git pull
    - git push --mirror https://kishore-koii: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@github.com/koii-network/testing-gitlab.git
  only:
    - master
