sync-to-github:
  image: alpine/git
  script:
    - git clone --bare https://gitlab.com/kishore1307/blog.git
    - cd kishore1307/blog.git
    - git push --mirror https://github.com/kishore1307/blob.git
  only:
    - master